config/routes.rb
Rails.application.routes.draw do
	
  resources :users

  resources :tickets

  get 'home/index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
validates :event_title, presence: true, length: { minimum: 1 }
validates :event_type, presence: true, length: { minimum: 1 }
validates :venue, presence: true, length: { minimum: 1 }
validates :date, presence: true, length: { minimum: 1 }
validates :time, presence: true, length: { minimum: 1 }
validates :tickets_available, presence: true, length: { minimum: 1 }
validates :total_tickets, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
 
  validates_uniqueness_of :email
end

app/models/user_booking.rb
class UserBooking < ActiveRecord::Base
validates :event_title, presence: true, length: { minimum: 1 }
validates :event_type, presence: true, length: { minimum: 1 }
validates :venue, presence: true, length: { minimum: 1 }
validates :date, presence: true, length: { minimum: 1 }
validates :time, presence: true, length: { minimum: 1 }
validates :tickets_available, presence: true, length: { minimum: 1 }
validates :total_tickets, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tickets_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	def index
		@tickets = Ticket.all
	end
	
	def new
		@ticket = Ticket.new
	end

	def create
		@ticket = Ticket.new(ticket_params)
		@ticket.save
		redirect_to @ticket
	end

	def edit
		@ticket = Ticket.find(params[:id])
	end

	def update
		@ticket = Ticket.find(params[:id])
		if @ticket.update(ticket_params)
			redirect_to @ticket
		else
			render 'edit'
		end
	end

	def show
		@ticket = Ticket.find(params[:id])
	end

	private
		def ticket_params
			params.require(:ticket).permit(:event_title, :event_type, :venue, :date, :time, :tickets_available, :total_tickets) 
		end
end

app/controllers/users_bookings_controller.rb
class UsersBookingsController < ApplicationController

	def index
		@tickets = Ticket.all
	end
	
	def new
		@ticket = Ticket.new
	end

	def create
		@ticket = Ticket.new(ticket_params)
		@ticket.save
		redirect_to @ticket
	end

	def edit
		@ticket = Ticket.find(params[:id])
	end

	def update
		@ticket = Ticket.find(params[:id])
		if @ticket.update(ticket_params)
			redirect_to @ticket
		else
			render 'edit'
		end
	end

	def show
		@ticket = Ticket.find(params[:id])
	end

	private
		def ticket_params
			params.require(:ticket).permit(:event_title, :event_type, :venue, :date, :time, :tickets_available, :total_tickets) 
		end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tickets_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_bookings_helper.rb
module UsersBookingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:500%;
              
          }
</style>


</head>
<hr>
<body>

<center>
  <h1>URtickets.com</h1>
 

<%= image_tag("logo.JPG" ,  :width => 400, :height => 150, :crop => :fill) %>

  <p>Thank you for choosing URtickets!. </p>
  <p> Please come again. </p>
  

</body>
</center>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_header">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/edit.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:300%;
              
          }
</style>


<h1>Edit a Ticket</h1>

<%= form_for :ticket, url:tickets_path(@ticket), method: patch do do |f| %>

 <% if @ticket.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited
      this ticket from being sold:</h2>
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :event_title %><br>
    <%= f.text_field :event_title %>
  </p>

  <p>
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </p>

  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>
 
  <p>
    <%= f.label :tickets_available %><br>
    <%= f.text_field :tickets_available %>
  </p>

  <p>
    <%= f.label :total_tickets %><br>
    <%= f.text_field :total_tickets %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:300%;
              
          }

  h2   {
  
          color:green;
          font-size:200%;
              
          }
          
  h3   {
  
          color:red;
          font-size:200%;
              
          }
</style>


<h1>Listing Of Tickets</h1>
<hr>



<body>


<h2>Available Tickets</h2>

<%= image_tag("images1.jpg" ) %>



<table>
  <tr>
    <th>Event Photo:</th>
    <th>Event Title:</th>
    <th colspan=2=></th>
  </tr>
 
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= image_tag("images3.jpg",  :width => 85, :height => 60, :crop => :fill) %></td>     
      <td><%= link_to ticket.event_title, ticket_path(ticket) %></td>
    </tr>
  <% end %>
</table>

<h3>Booked Tickets</h3>
<%= image_tag("images2.jpg") %>

</html>

app/views/tickets/new.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:300%;
              
          }
</style>




<h1>Add Tickets For Sale</h1>

<%= form_for :ticket, url:tickets_path do |f| %>

 <% if @ticket.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited
      this ticket from being sold:</h2>
    <ul>
    <% @ticket.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :event_title %><br>
    <%= f.text_field :event_title %>
  </p>

  <p>
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </p>

  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>
 
  <p>
    <%= f.label :tickets_available %><br>
    <%= f.text_field :tickets_available %>
  </p>

  <p>
    <%= f.label :total_tickets %><br>
    <%= f.text_field :total_tickets %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:300%;
              
          }
</style>


<h1>Ticket Details</h1>

<p>
<strong>Event Title:</strong> <%= @ticket.event_title %>
</p>

<p>
<strong>Event Type:</strong> <%= @ticket.event_type %>
</p>

<p>
<strong>Venue:</strong> <%= @ticket.venue %>
</p>

<p>
<strong>Date:</strong> <%= @ticket.date %>
</p>

<p>
<strong>Time:</strong> <%= @ticket.time %>
</p>

<p>
<strong>Tickets Available:</strong> <%= @ticket.tickets_available %>
</p>

<p>
<strong>Tickets Total:</strong> <%= @ticket.total_tickets %>
</p>


<%= link_to 'Back', tickets_path %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>

<head>
<style>
  body {background-color:lightgrey}
  h1   {
  
          color:blue;
          font-size:300%;
              
          }
</style>


<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <br>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <br>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>